FROM node:16-alpine
LABEL authors="Oleg"

USER node

RUN mkdir -p /home/node/appf
WORKDIR /home/node/app
COPY --chown=node:node ./package.json ./

RUN npm install
COPY --chown=node:node ./ ./
CMD ["npm", "run", "start"]