FROM node:16-alpine
ENV CI=true
ENV WDS_SOCKET_PORT=0
LABEL authors="Oleg"

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node ./package.json ./

RUN npm install
COPY --chown=node:node ./ ./
CMD ["npm", "run", "start"]