apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: java-cherkasy-com-tls
spec:
  secretName: java-cherkasy-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: java-cherkasy.com
  dnsNames:
    - java-cherkasy.com
    - www.java-cherkasy.com